// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class CraftingOrderItem : ICraftingOrderItem
    {
        public System.Nullable<ulong> OrderItemID { get; set; }
        public System.Nullable<int> OrderItemType { get; set; }
        public WowGuid ItemGUID { get; set; }
        public WowGuid OwnerGUID { get; set; }
        public ICraftingReagentBase Reagent { get; set; }
        public System.Nullable<uint> Quantity { get; set; }
        public System.Nullable<int> ReagentQuality { get; set; }
        public System.Nullable<uint> Flags { get; set; }
        public System.Nullable<byte> DataSlotIndex { get; set; }
    }
}

