// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class DelveData : IDelveData
    {
        public int MapID { get; set; }
        public int Tier { get; set; }
        public ulong InstanceID { get; set; }
        public int EntranceType { get; set; }
        public WowGuid[] PlayersEligibleForRewards { get; set; }
        public int[] ActiveOptionalAffixIDs { get; set; }
        public uint RestrictingRewardPlayers { get; set; }
        public uint IsLfg { get; set; }
    }
}

