// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class DynamicObjectData : IDynamicObjectData
    {
        public WowGuid Caster { get; set; }
        public System.Nullable<byte> Type { get; set; }
        public System.Nullable<int> SpellXSpellVisualID { get; set; }
        public System.Nullable<int> SpellID { get; set; }
        public System.Nullable<float> Radius { get; set; }
        public System.Nullable<uint> CastTime { get; set; }
    }
}

