// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class NPCAsPlayerInfo : INPCAsPlayerInfo
    {
        public int Field_0 { get; set; }
        public int CharacterLoadoutID { get; set; }
        public int CreatureID { get; set; }
        public Vector3 LocWorldSpace { get; set; }
        public float FacingWorldSpace { get; set; }
        public WowGuid TransportGUID { get; set; }
    }
}

