// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class SceneObjectData : ISceneObjectData
    {
        public System.Nullable<int> ScriptPackageID { get; set; }
        public System.Nullable<uint> RndSeedVal { get; set; }
        public WowGuid CreatedBy { get; set; }
        public System.Nullable<uint> SceneType { get; set; }
    }
}

