// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class TransmogOutfitData : ITransmogOutfitData
    {
        public System.Nullable<uint> Id { get; set; }
        public ITransmogOutfitDataInfo OutfitInfo { get; set; }
        public System.Nullable<uint> Flags { get; set; }
        public DynamicUpdateField<ITransmogOutfitSituationInfo> Situations { get; } = new();
        public DynamicUpdateField<ITransmogOutfitSlotData> Slots { get; } = new();
    }
}

