// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class TransmogOutfitMetadata : ITransmogOutfitMetadata
    {
        public byte SituationTrigger { get; set; }
        public uint TransmogOutfitID { get; set; }
        public byte StampedOptionMainHand { get; set; }
        public byte StampedOptionOffHand { get; set; }
        public float CostMod { get; set; }
        public bool Locked { get; set; }
    }
}

