// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class TransmogOutfitSlotData : ITransmogOutfitSlotData
    {
        public System.Nullable<sbyte> Slot { get; set; }
        public System.Nullable<byte> SlotOption { get; set; }
        public System.Nullable<byte> SheatheCategory { get; set; }
        public System.Nullable<uint> ItemModifiedAppearanceID { get; set; }
        public System.Nullable<byte> AppearanceDisplayType { get; set; }
        public System.Nullable<uint> SpellItemEnchantmentID { get; set; }
        public System.Nullable<byte> IllusionDisplayType { get; set; }
        public System.Nullable<uint> Flags { get; set; }
    }
}

