// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V1_60_1_70009.UpdateFields.V1_60_1_70009
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class VisibleItem : IMutableVisibleItem
    {
        public System.Nullable<int> ItemID { get; set; }
        public System.Nullable<int> SecondaryItemModifiedAppearanceID { get; set; }
        public System.Nullable<int> ConditionalItemAppearanceID { get; set; }
        public System.Nullable<ushort> ItemAppearanceModID { get; set; }
        public System.Nullable<ushort> ItemVisual { get; set; }
        public System.Nullable<uint> ItemModifiedAppearanceID { get; set; }
        public System.Nullable<byte> TransmogSlotOption { get; set; }
        public System.Nullable<byte> SheatheCategory { get; set; }
        public System.Nullable<bool> HasTransmog { get; set; }
        public System.Nullable<bool> HasIllusion { get; set; }
    }
}

